{ id: '57',
  title: 'Blog post title',
  date: '2016-12-16T12:03:47.000Z',
  modified: '2016-12-16T12:03:47.000Z',
  status: 'draft',
  type: 'post',
  name: '',
  author: '114424725',
  password: '',
  excerpt: '',
  content: '<div class="post_title"><img class="alignnone size-full wp-image-59" src="https://yourblog.files.wordpress.com/2016/12/dsc_0661.jpg" alt="dsc_0661" width="6000" height="4000" /></div>\n<div class="post_title">Blog Post title - imported from tumblr</div>\n<!--more-->\n<div class="post_body">\n\nsome text\n\nmore text\n\n</div>',
  parent: '0',
  link: 'https://yourblog.wordpress.com/?p=57',
  menuOrder: 0,
  commentStatus: 'open',
  pingStatus: 'open',
  sticky: false,
  thumbnail: [],
  format: 'standard',
  terms:
   [ { term_id: '1',
       name: 'Uncategorized',
       slug: 'uncategorized',
       term_group: '0',
       term_taxonomy_id: '1',
       taxonomy: 'category',
       description: '',
       parent: '0',
       count: 31,
       filter: 'raw' } ],
  customFields: [] }
